package pt.ptinovacao.arqospocket.service.enums;

public enum EEvent {
	HANDOVER, REGISTER_STATUS, PLMN_CHANGE, ROAMING_STATUS, PAUSE_SCAN,
	RESUME_SCAN, NO_NETWORKS_DETECTED, CELL_RESELECTION, CALL_SETUP,
	EMON_POCKET, CALL_ESTABLISHED, CALL_END, CALL_DROP, CALL_RELEASE

}
