package PT.PTInov.ArQoSPocketEDP.JSONConnector.Util;

public enum EnumParamTest {
	E2E_RESULT, E2E_CAUSE, E2E_NETWORK, E2E_TYPE, E2E_MSISDN, E2E_IP, E2E_IP_PKT_TX, E2E_IP_PKT_RX, E2E_IP_RTD_MAX, E2E_IP_RTD_AVG, E2E_IP_LOSS, E2E_SMS_MODEM_RESPONSE
}
